const DataGridColumns = [
  {
    field: 'id',
    headerName: 'Transaction ID',
    headerAlign: 'center',
    description: 'Unique Transaction ID for this transaction.',
    align: 'center',
    width: 210,
    hide: true,
  },
  {
    field: 'userId',
    headerName: 'User ID',
    headerAlign: 'center',
    description: 'User ID',
    align: 'center',
    width: 210,
    hide: true,
  },
  {
    field: 'userName',
    headerName: 'Name',
    headerAlign: 'center',
    description: 'User Name',
    align: 'center',
    width: 200,
    hide: true,
  },
  {
    field: 'userEmail',
    headerName: 'Email',
    headerAlign: 'center',
    description: 'User Email',
    align: 'center',
    width: 200,
    hide: true,
  },
  {
    field: 'depositoryName',
    headerName: 'Depository Name',
    headerAlign: 'center',
    description: 'The Depository in which you have invested.',
    align: 'center',
    width: 200,
    hide: true,
  },
  {
    field: 'companyName',
    headerName: 'Company Name',
    headerAlign: 'center',
    description: 'The company in which you have invested.',
    align: 'center',
    width: 300,
    hide: false,
  },
  // {
  //   field: 'googleSymbol',
  //   headerName: 'Google Symbol',
  //   headerAlign: 'center',
  //   description: 'Google Symbol for the Comapny.',
  //   width: 150,
  //   hide: true,
  // },
  {
    field: 'yahooSymbol',
    headerName: 'Yahoo Symbol',
    headerAlign: 'center',
    description: 'Yahoo Symbol for the Company.',
    align: 'center',
    width: 150,
    hide: true,
  },
  {
    field: 'buyDate',
    headerName: 'Buy Date',
    headerAlign: 'center',
    description: 'Date on which you have purchased the Shares.',
    align: 'center',
    width: 120,
    hide: false,
  },
  {
    field: 'noOfShares',
    headerName: 'Shares',
    headerAlign: 'center',
    description: 'Number of Shares you have purchased.',
    align: 'center',
    width: 100,
    hide: false,
  },
  {
    field: 'priceOfShareAtBuy',
    headerName: 'Buy Price',
    headerAlign: 'center',
    description: 'The price of each share when bought.',
    align: 'center',
    width: 150,
    hide: false,
  },
  {
    field: 'priceOfShareAtToday',
    headerName: 'Price Today',
    headerAlign: 'center',
    description: 'The price of share today, unless updated.',
    align: 'center',
    width: 150,
    hide: false,
  },
  {
    field: 'totalInvestedAmount',
    headerName: 'Invested Amount',
    headerAlign: 'center',
    description: 'Total Invested Amount in this Company for this Transaction.',
    align: 'center',
    width: 150,
    hide: false,
  },
  {
    field: 'totalCurrentAmount',
    headerName: 'Current Amount',
    headerAlign: 'center',
    description: 'Total Current Amount in this Company for this Transaction, unless updated.',
    align: 'center',
    width: 150,
    hide: false,
  },
  {
    field: 'PNLTillDate',
    headerName: 'P/L',
    headerAlign: 'center',
    description: 'Profit / Loss till date, unless updated.',
    align: 'center',
    width: 100,
    hide: false,
  },
  {
    field: 'investedTerm',
    headerName: 'Investment Term',
    headerAlign: 'center',
    description: 'The period of Investment.',
    align: 'center',
    width: 150,
    hide: true,
  },
  {
    field: 'rateOfReturn',
    headerName: 'Rate of Return',
    headerAlign: 'center',
    description: 'Simple Rate of Return (ROR).',
    align: 'center',
    width: 150,
    hide: true,
  },
  {
    field: 'RORAnnualized',
    headerName: 'ROR Annualized',
    headerAlign: 'center',
    description: 'Annualized Rate of Return (CAGR).',
    align: 'center',
    width: 150,
    hide: true,
  },
  {
    field: 'priceChangePerShare',
    headerName: 'Price Change',
    headerAlign: 'center',
    description: 'The change of price per share since yesterday.',
    align: 'center',
    width: 150,
    hide: true,
  },
  {
    field: 'percentageChangePerShare',
    headerName: '% Change',
    headerAlign: 'center',
    description: 'The percentage change of share price since yesterday.',
    align: 'center',
    width: 150,
    hide: true,
  },
  {
    field: 'priceChangeTotalShares',
    headerName: 'Total Price Change',
    headerAlign: 'center',
    description: 'The change of price for total shares since yesterday.',
    align: 'center',
    width: 150,
    hide: true,
  },
  {
    field: 'lastUpdatedTS',
    headerName: 'Last Updated On',
    headerAlign: 'center',
    description: 'Last Update Status',
    align: 'center',
    width: 200,
    hide: true,
  },
];

export default DataGridColumns;
