const DataGridColumns = [
  {
    field: 'transactionId',
    headerName: 'Transaction ID',
    headerAlign: 'center',
    description: 'Unique Transaction ID for this transaction.',
    width: 150,
    hide: true,
  },
  {
    field: 'userId',
    headerName: 'User ID',
    headerAlign: 'center',
    description: 'User ID',
    width: 150,
    hide: true,
  },
  { field: 'userName', headerName: 'Name', headerAlign: 'center', description: 'User Name', width: 150, hide: true },
  { field: 'userEmail', headerName: 'Email', headerAlign: 'center', description: 'User Email', width: 150, hide: true },
  {
    field: 'depositoryName',
    headerName: 'DepositoryName',
    headerAlign: 'center',
    description: 'The Depository in which you have invested.',
    width: 150,
    hide: false,
  },
  {
    field: 'companyName',
    headerName: 'CompanyName',
    headerAlign: 'center',
    description: 'The company in which you have invested.',
    width: 150,
    hide: false,
  },
  {
    field: 'googleSymbol',
    headerName: 'Google Symbol',
    headerAlign: 'center',
    description: 'Google Symbol for the Comapny.',
    width: 150,
    hide: true,
  },
  {
    field: 'yahooSymbol',
    headerName: 'Yahoo Symbol',
    headerAlign: 'center',
    description: 'Yahoo Symbol for the Company.',
    width: 150,
    hide: true,
  },
  {
    field: 'buyDate',
    headerName: 'Buy Date',
    headerAlign: 'center',
    description: 'Date on which you have purchased the Shares.',
    width: 150,
    hide: false,
  },
  {
    field: 'noOfShares',
    headerName: 'Number of Shares',
    headerAlign: 'center',
    description: 'Number of Shares you have purchased.',
    width: 150,
    hide: false,
  },
  {
    field: 'priceOfShareAtBuy',
    headerName: 'Share Price',
    headerAlign: 'center',
    description: 'The price of each share when bought.',
    width: 150,
    hide: false,
  },
  {
    field: 'priceOfShareAtToday',
    headerName: 'Share Price Today',
    headerAlign: 'center',
    description: 'The price of share today, unless updated.',
    width: 150,
    hide: false,
  },
  {
    field: 'totalInvestedAmount',
    headerName: 'Invested Amount',
    headerAlign: 'center',
    description: 'Total Invested Amount in this Company for this Transaction.',
    width: 150,
    hide: false,
  },
  {
    field: 'totalCurrentAmount',
    headerName: 'Current Amount',
    headerAlign: 'center',
    description: 'Total Current Amount in this Company for this Transaction, unless updated.',
    width: 150,
    hide: false,
  },
  {
    field: 'PNLTillDate',
    headerName: 'P/L',
    headerAlign: 'center',
    description: 'Profit / Loss till date, unless updated.',
    width: 150,
    hide: false,
  },
  {
    field: 'investedTerm',
    headerName: 'Investment Term',
    headerAlign: 'center',
    description: 'The period of Investment.',
    width: 150,
    hide: false,
  },
  {
    field: 'RORAnnualized',
    headerName: 'ROR Annuaized',
    headerAlign: 'center',
    description: 'Annualized Rate of Return',
    width: 150,
    hide: false,
  },
  {
    field: 'priceChangePerShare',
    headerName: 'Price Change',
    headerAlign: 'center',
    description: 'The change of price per share since yesterday.',
    width: 150,
    hide: false,
  },
  {
    field: 'percentageChangePerShare',
    headerName: '% Change',
    headerAlign: 'center',
    description: 'The percentage change of share price since yesterday.',
    width: 150,
    hide: false,
  },
  {
    field: 'priceChangeTotalShares',
    headerName: 'Price Change for Each',
    headerAlign: 'center',
    description: 'The change of price for total shares since yesterday.',
    width: 150,
    hide: false,
  },
  {
    field: 'lastUpdated',
    headerName: 'Last Updated On',
    headerAlign: 'center',
    description: 'Last Update Status',
    width: 150,
    hide: false,
  },
];

export default DataGridColumns;
